name :  Pull Deployment 
on: 
 pull_request:
  types: 
    - opened  # event/trigger comprises of every thing open,renew etc- but can not close , so we will be using activity types which will give us more control 
    - merged
    - closed
  workflow_dispatch:
  push:
   branches:
     - main # branches is a filter used to filter out branches another way of having more control to workflow 
jobs:
  main:
   runs-on: ubuntu-latest
   steps:
    - name: Name of the event 
      run: echo "my event specifications ${{ toJSON(github.event)}}"
    - name: Importing code
      uses: actions/checkout@v7
    - name: Building My Project
      run: echo "building your code"
    - name: Deploying My Code 
      run: echo "Deploying my code"

